version: '3'

services:
  redmine:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/redmine
    environment:
      RAILS_ENV: development
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - ./mysql_data:/var/lib/mysql
